FROM python:3.11-slim
WORKDIR /app
COPY orchestration/dagster/requirements.txt .
RUN pip install --no-cache-dir --timeout=600 --retries=5 -r requirements.txt
COPY orchestration/dagster/ .
COPY great_expectations/ ./great_expectations/
ENV DAGSTER_HOME=/app/dagster_home
ENV GE_ROOT=/app/great_expectations
ENV PYTHONPATH=/app
RUN mkdir -p /app/dagster_home
EXPOSE 4000
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "/app/definitions.py"]